### ISSUE TITLE
Second volume

### ISSUE THREAD

**Issue by idenkov** [willtho89/docker-samba-timemachine#2]
Hi,

Is it possible to create secondary volume with the same container?

**Comment by willtho89** [comment]
It’s not possible right now. You could start a second container to have multiple time machine destinations

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by idenkov** [comment]
Thanks, but running second container does not work if you already have one with docker-compose, even if stopped and change all the settings the seconds container keep mounting /timemachine volume. Will look for some other solution.

**Comment by willtho89** [comment]
You can probably run something like:
```sh
docker-compose up --scale app=2
```
However I'm not sure if docker-compose would create a separate volume for each app. In this case you'd need to change the compose file to create specific named volumes.

**Comment by idenkov** [comment]
I tried running just a container with adjusted configs for second volume, but that does not work. It keeps sharing file with the TimeMachine name in the local that is not accessible even after I have changed smb.cnf and all the other configurations.

**Comment by idenkov** [comment]
Thanks for all the help, I actually ended just using samba on the host. I don't think the solution with the second container will work out of the box because of the avahi and also the containers will have to occupy the same port.
