### ISSUE TITLE
Question: Can we have multiple users?

### ISSUE THREAD

**Issue by woutersamaey** [willtho89/docker-samba-timemachine#5]
Question: Can we have multiple users?

**Comment by willtho89** [comment]
@woutersamaey currently its not possible to have multiple users.
Maybe you can adjust the setup.sh to loop over multiple TM_USER variables. I'm open for Pull Requests

**Comment by woutersamaey** [comment]
OK I'll look into it when my new server arrives.

**Comment by willtho89** [comment]
ok I'll close this for now
