### ISSUE TITLE
Doesn't start on Raspberry Pi

### ISSUE THREAD

**Issue by Vannixxo** [willtho89/docker-samba-timemachine#7]
I can't make it work on Raspberry Pi 4 with or without composer, it always tries to restart

**Comment by willtho89** [comment]
I don’t have a spare rpi around. Could you please provide the console log?

**Comment by Vannixxo** [comment]
Yes of course, here it is:


`standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
`

**Comment by willtho89** [comment]
can you try to change the first line in `Dockerfile` to `FROM arm32v6/alpine`?
This should get the binaries for arm platforms (like rpi).

**Comment by Vannixxo** [comment]
I downloaded the files, edited the Dockerfile and built my image then created the container with composer and it works!
